name: Build wheels

on:
 push:
 workflow_call:

jobs:

 checkout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Upload checkout
      uses: actions/upload-artifact@v3
      with:
        name: checkout
        path: .

 build-linux:
  needs: checkout
  runs-on: ubuntu-latest
  strategy:
    matrix:
      image:
        #- "quay.io/pypa/manylinux1_x86_64"
        #- "quay.io/pypa/manylinux1_i686"
        - "quay.io/pypa/manylinux2014_x86_64"
      redis_version:
        # - "5.0.10"
        # - "6.0.9"
        - "6.2.5"
      python_version:
        - "3.9"
      include:
        - python_version: "3.9"
          abi_tag: "cp39-cp39"

  container:
    image: ${{ matrix.image }}
    options: --user 1001
  steps:
    - name: Download checkout
      uses: actions/download-artifact@v3
      with:
        name: checkout
        path: .

    - name: Fix +x permission
      run: find tools/ -type f -iname "*.sh" -exec chmod +x {} \;
    - name: Setup poetry
      run: |
        export POETRY_HOME=/opt/poetry
        curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.6.1 /opt/python/${{ matrix.abi_tag }}/bin/python -
        update-alternatives --install /usr/bin/poetry poetry $POETRY_HOME/bin/poetry 0
        poetry --version
        poetry config virtualenvs.create false

    - name: Build redis
      run: tools/build.sh ${{ matrix.redis_version }} redis_wheel/bin

    - name: List dist/
      run: ls -R dist/
    - name: Build distribution
      run: |
        tools/distrib.sh \
          $(pwd) \
          ${{ matrix.redis_version }} \
          ${{ matrix.abi_tag }} \
          $(echo ${{ matrix.image }} | awk -F'/' '{print $(NF)}')

    - name: Upload distribution
      uses: actions/upload-artifact@v3
      with:
        name: distribution
        path: dist/

 build-macos:
  needs: checkout
  runs-on: macOS-11
  strategy:
    matrix:
      redis_version:
        #- "5.0.10"
        #- "6.0.9"
        - "6.2.5"
      python_version:
        - "3.9"
      include:
        - python_version: "3.9"
          abi_tag: "cp39-cp39"
  steps:
    - name: Download checkout
      uses: actions/download-artifact@v3
      with:
        name: checkout
        path: .

    - name: Fix +x permission
      run: find tools/ -type f -iname "*.sh" -exec chmod +x {} \;

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install poetry
      run: pipx install poetry

    - name: Build redis
      run: tools/build.sh ${{ matrix.redis_version }} redis_wheel/bin

    - name: Build distribution
      run: |
        tools/distrib.sh \
          $(pwd) \
          ${{ matrix.redis_version }} \
          ${{ matrix.abi_tag }} \
          macosx_11_0_x86_64

    - name: Upload distribution
      uses: actions/upload-artifact@v3
      with:
        name: distribution
        path: dist/
