name: build-and-publish

on:
 push:

jobs:

 checkout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Upload checkout
      uses: actions/upload-artifact@v1
      with:
        name: checkout
        path: .

 build-linux:
  needs: checkout
  runs-on: ubuntu-latest
  strategy:
    matrix:
      image:
        - "quay.io/pypa/manylinux1_x86_64"
        #- "quay.io/pypa/manylinux1_i686"
        - "quay.io/pypa/manylinux2010_x86_64"
        #- "quay.io/pypa/manylinux2010_i686"
      redis_version:
        # - "5.0.10"
        # - "6.0.9"
        - "6.2.5"
      python_version:
        - "3.9"
      include:
        - python_version: "3.9"
          python_abi: "cp39"

  container:
    image: ${{ matrix.image }}
  steps:
    - name: Download checkout
      uses: actions/download-artifact@v1
      with:
        name: checkout
        path: .

    - name: Fix +x permission
      run: find tools/ -type f -iname "*.sh" -exec chmod +x {} \;

    - name: Setup python ${{ matrix.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        update-alternatives --install /usr/bin/poetry poetry $HOME/.poetry/bin/poetry 0
        poetry --version
        poetry config virtualenvs.create false

    - name: Build redis
      run: tools/build.sh ${{ matrix.redis_version }} redis_wheel/bin

    - name: Build distribution
      run: |
        tools/distrib.sh \
          $(pwd) \
          ${{ matrix.redis_version }} \
          ${{ matrix.python_abi }} \
          $(echo ${{ matrix.image }} | awk -F'/' '{print $(NF)}')

    - name: Upload distribution
      uses: actions/upload-artifact@v1
      with:
        name: distribution
        path: dist/

 build-macos:
  needs: checkout
  runs-on: macos-10.15
  strategy:
    matrix:
      redis_version:
        #- "5.0.10"
        #- "6.0.9"
        - "6.2.5"
  steps:
    - name: Download checkout
      uses: actions/download-artifact@v1
      with:
        name: checkout
        path: .

    - name: Fix +x permission
      run: find tools/ -type f -iname "*.sh" -exec chmod +x {} \;

    - name: Setup python
      uses: actions/setup-python@v1

    - name: Setup pip/poetry
      run: |
        pip install -U pip poetry
        pip --version
        poetry --version

    - name: Build redis
      run: tools/build.sh ${{ matrix.redis_version }} redis_wheel/bin

    - name: Build distribution
      run: |
        tools/distrib.sh \
          $(pwd) \
          ${{ matrix.redis_version }} \
          py3-none \
          macosx_10_15_x86_64

    - name: Upload distribution
      uses: actions/upload-artifact@v1
      with:
        name: distribution
        path: dist/

 publish:
  needs: [build-linux, build-macos]
  runs-on: ubuntu-latest
  steps:
    - name: Download distribution
      uses: actions/download-artifact@v1
      with:
        name: distribution
        path: dist/

    - name: Setup python
      uses: actions/setup-python@v1

    - name: Setup pip/twine
      run: |
        pip install -U pip twine
        pip --version
        twine --version

    - name: Upload distributions
      run: |
        twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
