name: manylinux

on:
 push:

jobs:
 
 checkout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Upload checkout
      uses: actions/upload-artifact@v1
      with:
        name: checkout
        path: .

 build:
  needs: checkout
  runs-on: ubuntu-latest
  strategy:
    matrix:
      image:
        - "quay.io/pypa/manylinux1_x86_64"
        - "quay.io/pypa/manylinux1_i686"
      redis_version:
        - "5.0.7"
        - "5.0.6"
  container:
    image: ${{ matrix.image }}
  steps:
    - name: Download checkout
      uses: actions/download-artifact@v1
      with:
        name: checkout
        path: .
    - name: debug
      run: |
        ls -alh
        echo $(echo ${{ matrix.image }} | awk -F'/' '{print $(NF)}')
        echo ${{ matrix.redis_version }}
