name: Publish Wheels

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  run-build-workflow:
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: distribution
        path: dist/
    - name: List artifacts downloaded
      run: ls -R dist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1.8
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
